"""Setup wizard helpers for Agent2."""

from __future__ import annotations

import json
import secrets
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

DEFAULT_MODEL = "~anthropic/claude-sonnet-latest"
MODEL_CHOICES = (
    "~anthropic/claude-sonnet-latest",
    "~openai/gpt-latest",
    "~moonshotai/kimi-latest",
    "~openai/gpt-mini-latest",
    "~anthropic/claude-opus-latest",
)


@dataclass(frozen=True)
class SetupOptions:
    openrouter_api_key: str = ""
    default_model: str = DEFAULT_MODEL
    stack_profile: str = "core"
    telemetry_enabled: bool = False
    no_docker: bool = False
    no_onboard: bool = False
    yes: bool = False
    dry_run: bool = False
    json_output: bool = False


def setup_payload(options: SetupOptions) -> dict[str, Any]:
    """Return the files and values that setup would create."""

    token = secrets.token_urlsafe(32)
    env = {
        "OPENROUTER_API_KEY": options.openrouter_api_key,
        "DEFAULT_MODEL": options.default_model,
        "AGENT2_STACK_PROFILE": options.stack_profile,
        "AGENT2_TELEMETRY_ENABLED": str(options.telemetry_enabled).lower(),
        "API_BEARER_TOKEN": token,
        "REDIS_AUTH": secrets.token_urlsafe(18),
        "POSTGRES_PASSWORD": secrets.token_urlsafe(18),
        "LANGFUSE_NEXTAUTH_SECRET": secrets.token_urlsafe(32),
        "LANGFUSE_SALT": secrets.token_urlsafe(24),
        "LANGFUSE_ENCRYPTION_KEY": secrets.token_hex(32),
    }
    config = {
        "default_model": options.default_model,
        "provider_order": _provider_order_for_model(options.default_model),
        "provider_policy": {"allow_fallbacks": False},
        "stack_profile": options.stack_profile,
        "telemetry": {"enabled": options.telemetry_enabled},
        "ports": {"agent_start": 8014, "setup_ui": 8787},
    }
    return {"env": env, "agent2": config}


def _provider_order_for_model(model_id: str) -> list[str]:
    """Infer an OpenRouter provider pin from a model alias or model id."""

    if model_id.startswith("~"):
        return [model_id[1:].split("/", 1)[0]]
    if model_id.startswith("openrouter/"):
        return [model_id.removeprefix("openrouter/").split("/", 1)[0]]
    return []


def run_setup(project_root: Path, options: SetupOptions) -> dict[str, Any]:
    """Write setup files and optionally start Docker."""

    payload = setup_payload(options)
    if options.dry_run:
        return {"changed": False, "dry_run": True, **payload}

    _write_env(project_root / ".env", payload["env"])
    _write_yaml(project_root / "agent2.yaml", payload["agent2"])

    docker_started = False
    if not options.no_docker:
        command = ["docker", "compose"]
        if options.stack_profile == "full":
            command += ["--profile", "full"]
        command += ["up", "-d"]
        subprocess.run(command, cwd=project_root, check=True)
        docker_started = True

    return {"changed": True, "dry_run": False, "docker_started": docker_started, **payload}


def _backup(path: Path) -> None:
    if not path.exists():
        return
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    shutil.copy2(path, path.with_suffix(path.suffix + f".bak-{stamp}"))


def _write_env(path: Path, values: dict[str, str]) -> None:
    _backup(path)
    lines = ["# Generated by agent2 setup", ""]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_yaml(path: Path, values: dict[str, Any]) -> None:
    _backup(path)
    path.write_text(yaml.safe_dump(values, sort_keys=False), encoding="utf-8")


def payload_as_json(payload: dict[str, Any]) -> str:
    redacted = json.loads(json.dumps(payload))
    if redacted.get("env", {}).get("OPENROUTER_API_KEY"):
        redacted["env"]["OPENROUTER_API_KEY"] = "***"
    return json.dumps(redacted, indent=2)
